name = "shortener-worker"
compatibility_date = "2024-12-01"

main = "src/index.js"

[[d1_databases]]
binding = "DB"
database_name = "shortener-db"
database_id = "5b07ee93-1aaa-4199-a48f-5c166e380456"
